# Generated by Django 5.0.6 on 2024-10-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrt_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('user', 'user')], max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
