# Generated by Django 5.0.6 on 2024-10-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0002_userregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='fisrt_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='user_type',
            field=models.CharField(choices=[('user', 'user')], default='user', max_length=50),
        ),
    ]
