# Generated by Django 5.0.6 on 2024-10-30 19:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0005_rename_description_game_summary_remove_game_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentspecs',
            name='game',
        ),
        migrations.RemoveField(
            model_name='currentspecs',
            name='processor',
        ),
        migrations.AddField(
            model_name='currentspecs',
            name='cpu',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='currentspecs',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='currentspecs',
            name='os_version',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='currentspecs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currentspecs',
            name='gpu',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='currentspecs',
            name='ram',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='currentspecs',
            name='storage',
            field=models.FloatField(default=0),
        ),
    ]
