# Generated by Django 5.0.6 on 2024-10-30 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0006_remove_currentspecs_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentspecs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamerapp.userregistration'),
        ),
    ]
