# Generated by Django 5.0.6 on 2024-11-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0008_alter_currentspecs_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('available_tournaments', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('platform', models.CharField(max_length=50)),
                ('website_url', models.URLField()),
                ('image', models.ImageField(upload_to='games/')),
            ],
        ),
    ]
