# Generated by Django 5.0.6 on 2024-11-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0009_tournament_upcominggame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='UpcomingGame',
        ),
    ]
