# Generated by Django 5.0.6 on 2024-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerapp', '0010_delete_tournament_delete_upcominggame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('available_tournaments', models.IntegerField()),
                ('image', models.ImageField(upload_to='tournaments/')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('platform', models.CharField(max_length=100)),
                ('website_url', models.URLField()),
                ('image', models.ImageField(upload_to='upcoming_games/')),
            ],
        ),
    ]
